---
title: "Data Tidying"
author: "Stephen Klobucar"
date: "October 16, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, warning=F, message=F}
library(dplyr)
library(tidyr)
library(DT)
```

Read in catch data from []https://knb.ecoinformatics.org/view/df35b.304.2

```{r}
catch_df <- read.csv(url("https://knb.ecoinformatics.org/knb/d1/mn/v2/object/df35b.302.1", method = "libcurl"),
                    stringsAsFactors = FALSE)
head(catch_df)
```

`select` columns needed for analyses  
`gather` to move from wide to long  
`rename` a column to indicate units  

```{r}
catch_clean <- catch_df %>% 
  #select(Region, Year, Chinook, Sockeye, Coho, Pink, Chum)
  select(-All, -notesRegCode) %>% 
  gather(key = 'species', value = 'catch', -Region, -Year) %>% 
  rename(catch_thousands = catch)

#head(catch_clean)
tail(catch_clean)
```



```{r}
test <- as.numeric(catch_clean$catch_thousands)

i <- which(is.na(test) == T)
print(i)

catch_clean[i,]
```
fix typo in original dataset  
coerce catch to numeric, convert to number of fish  
`mutate` to create a new catch column  

```{r}
catch_clean_mutated <- catch_clean %>% 
  mutate(catch_thousands = ifelse(catch_thousands == 'I', 1, catch_thousands)) %>% 
  mutate(catch_thousands = as.numeric(catch_thousands)) %>% 
  mutate(catch = catch_thousands * 1000) %>% 
  select(-catch_thousands)

#head(catch_clean_mutated)
tail(catch_clean_mutated)
```


split using `group_by`  
apply and combine using `summarize`  

```{r}
catch_summ <- catch_clean_mutated %>% 
  group_by(Region, species) %>% 
  summarize(mean_catch = mean(catch), max(catch),
            n_obs = n())

head(catch_summ)
```
```{r}
catch_chinook <- catch_clean_mutated %>% 
  filter(species == 'Chinook') %>% 
  arrange(-catch)

head(catch_chinook)

DT::datatable(catch_chinook)
```

#Joins
load regions data table
```{r}
region_defs <- read.csv(url("https://knb.ecoinformatics.org/knb/d1/mn/v2/object/df35b.303.1", method = "libcurl"),
                        stringsAsFactors = FALSE)

head(region_defs)
```

```{r}
region_defs <- region_defs %>% 
  select(code, mgmtArea)

head(region_defs)
```

```{r}
catch_joined <- left_join(catch_clean_mutated, region_defs, by = c("Region" = "code"))

head(catch_joined)
#inspect join
nrow(catch_joined)
nrow(catch_clean_mutated)
#another way
i <-  which(is.na(catch_joined$mgmtArea))
nrow(i)
```

```{r}
dates_df <- data.frame(date = c("5/24/1930",
                                "5/25/1930",
                                "5/26/1930",
                                "5/27/1930",
                                "5/28/1930"),
                       stringsAsFactors = FALSE)

dates_df %>% 
  separate(date, c("month", "day", "year"), "/") %>% 
  unite(col = date_iso, year, month, day, sep = '-')  ##but, month should be two digits

dates_df

```

